"""Top-level ``mlsweep`` command — one entry point for the whole workflow.

See ``_HELP`` for the subcommand list. This module is intentionally light at import time; heavy subcommands are
imported lazily so ``mlsweep --help`` stays fast.
"""

from __future__ import annotations

import argparse
import re
import sys
from collections.abc import Callable
from pathlib import Path

from mlsweep._shared import _CYAN, _GREEN, _RED, _RESET, _YELLOW, _mlsweep_dir

_ANSI_RE = re.compile(r"\x1b\[[0-9;]*m")


def _visible_width(s: str) -> int:
    """Visible width of *s* with ANSI escape sequences removed."""
    return len(_ANSI_RE.sub("", s))


def _pad(s: str, width: int) -> str:
    """Right-pad *s* to visible width *width*."""
    return s + " " * max(0, width - _visible_width(s))


def _align(rows: list[tuple[str, str]], indent: str = "  ") -> str:
    """Two-column table: left column padded to the widest, two spaces, right column."""
    width = max(_visible_width(left) for left, _ in rows)
    return "\n".join((f"{indent}{_pad(left, width)}  {right}").rstrip() for left, right in rows)


def _align3(rows: list[tuple[str, str, str]], indent: str = "  ") -> str:
    """Three-column table: command / argument / description, all aligned."""
    cw = max(_visible_width(c) for c, _, _ in rows)
    aw = max(_visible_width(a) for _, a, _ in rows)
    return "\n".join((f"{indent}{_pad(c, cw)}  {_pad(a, aw)}  {d}").rstrip() for c, a, d in rows)


_LABEL_WIDTH = 10
_CONT = " " * (2 + _LABEL_WIDTH + 2)


def _label(label: str) -> str:
    """Left-align a `key:` label to the shared label column."""
    return _pad(label, _LABEL_WIDTH) + "  "


def _build_help() -> str:
    workflow = [
        (f"1. {_GREEN}mlsweep manager{_RESET}", "start the persistent manager (once)"),
        (f"2. {_GREEN}mlsweep run my_sweep.py --stream{_RESET}", "submit a sweep (validate/dry-run first)"),
        (f"3. {_GREEN}mlsweep watch <experiment_id>{_RESET}", "live terminal status"),
        (f"4. {_GREEN}mlsweep fetch --experiment <id>{_RESET}", "download results + summary"),
        (f"5. {_GREEN}mlsweep status{_RESET}", "manager / token / GPU / result paths"),
    ]
    subcommands = [
        ("manager [args...]", "start the manager daemon (mlsweep_manager)"),
        ("run SWEEP.py [flags]", "submit a sweep (mlsweep_run)"),
        ("worker [args...]", "start a worker daemon (mlsweep_worker)"),
        ("watch EXP_ID", "live status for an experiment"),
        ("fetch", "download + summarize an experiment's results"),
        ("status | doctor", "diagnose the environment"),
        ("docs [topic]", "read the bundled runbook (README by default)"),
        ("gen_makefile", "write a standard Makefile into the current directory"),
        ("version", "print the version"),
    ]
    return "\n".join([
        f"{_CYAN}mlsweep{_RESET} — experiment sweep engine.",
        "",
        "Workflow:",
        _align(workflow),
        "",
        "Subcommands:",
        _align(subcommands),
        "",
        "watch/fetch/status default --manager to $MLSWEEP_MANAGER or http://localhost:7891;",
        "`run` requires --manager explicitly.",
        "Results live on the manager at ~/.mlsweep/experiments/<experiment_id>/<run>/",
        f"Docs: {_CYAN}mlsweep --help <topic>{_RESET} (readme, sweep_configuration, mlsweep, examples)",
        f"      or {_CYAN}mlsweep docs{_RESET}; {_CYAN}mlsweep gen_makefile{_RESET} adds {_CYAN}make sweep-*{_RESET} targets.",
    ]) + "\n"


_HELP = _build_help()

_DOC_ALIASES = {
    "readme": "README.md",
    "index": "README.md",
    "sweep_configuration": "sweep_configuration.md",
    "sweep_config": "sweep_configuration.md",
    "config": "sweep_configuration.md",
    "configuration": "sweep_configuration.md",
    "sweeps": "sweep_configuration.md",
    "mlsweep": "mlsweep.md",
    "skill": "mlsweep.md",
    "examples": "examples.md",
}

def _build_makefile_template() -> str:
    help_rows = [
        ("make sweep-manager", "", "start the manager daemon"),
        ("make sweep-status", "", "check manager health, GPUs, token"),
        ("make sweep-validate", "S=<path>", "validate a sweep file"),
        ("make sweep-dry-run", "S=<path>", "print commands without running"),
        ("make sweep-run", "S=<path>", "submit + stream live status"),
        ("make sweep-watch", "E=<id>", "watch an experiment"),
        ("make sweep-fetch", "E=<id>", "fetch results + summary"),
        ("make sweep-docs", "", "read the full runbook"),
    ]
    help_block = "\n".join(f'\t@echo "{line}"' for line in _align3(help_rows).split("\n"))
    return (
        "# Generated by `mlsweep gen_makefile`. Regenerate with `mlsweep gen_makefile --force`.\n"
        "# This is the standard mlsweep project interface. See `mlsweep docs` for the full runbook.\n"
        "\n"
        "MLSWEEP_MANAGER ?= http://localhost:7891\n"
        "S ?=\n"
        "E ?=\n"
        "\n"
        ".PHONY: help sweep-manager sweep-status sweep-docs sweep-validate sweep-dry-run sweep-run sweep-watch sweep-fetch sweep-gen\n"
        "\n"
        "help:\n"
        '\t@echo "mlsweep targets:"\n'
        f"{help_block}\n"
        "\n"
        "sweep-manager:\n"
        "\tmlsweep manager\n"
        "\n"
        "sweep-status:\n"
        "\tmlsweep status\n"
        "\n"
        "sweep-docs:\n"
        "\tmlsweep docs\n"
        "\n"
        "sweep-validate:\n"
        "\tmlsweep run $(S) --manager $(MLSWEEP_MANAGER) --validate\n"
        "\n"
        "sweep-dry-run:\n"
        "\tmlsweep run $(S) --manager $(MLSWEEP_MANAGER) --dry-run\n"
        "\n"
        "sweep-run:\n"
        "\tmlsweep run $(S) --manager $(MLSWEEP_MANAGER) --stream\n"
        "\n"
        "sweep-watch:\n"
        "\tmlsweep watch $(E) --manager $(MLSWEEP_MANAGER)\n"
        "\n"
        "sweep-fetch:\n"
        "\tmlsweep fetch --manager $(MLSWEEP_MANAGER) --experiment $(E)\n"
        "\n"
        "sweep-gen:\n"
        "\tmlsweep gen_makefile --force\n"
    )


_MAKEFILE_TEMPLATE = _build_makefile_template()


# ── status / doctor ────────────────────────────────────────────────────────────


def _status_cmd(argv: list[str]) -> None:
    from mlsweep.run_sweep import _add_manager_args, _http_request, _manager_url, _resolve_token
    from mlsweep.worker import _query_gpu_stats

    parser = argparse.ArgumentParser(
        prog="mlsweep status",
        description="Check the mlsweep environment: manager, token, GPUs, results.",
    )
    _add_manager_args(parser)
    args = parser.parse_args(argv)

    manager = args.manager.rstrip("/")
    token = _resolve_token(args.token)
    mlsweep_dir = _mlsweep_dir()
    token_file = mlsweep_dir / "manager.token"

    print(f"{_CYAN}mlsweep status{_RESET}")
    print(f"  {_label('manager:')}{manager}")
    print(f"  {_label('results:')}{mlsweep_dir / 'experiments'}")
    print(f"  {_label('dashboard:')}{manager}/?token=<token>")
    print()

    # ── Manager health ─────────────────────────────────────────────────────
    status, resp = _http_request("GET", _manager_url(manager, "/api/health"), token, timeout=10)
    if status == 0:
        print(f"  {_label('manager:')}{_RED}DOWN{_RESET} — no response from {manager}")
        print(f"{_CONT}start it with: {_GREEN}mlsweep manager{_RESET}")
    elif status == 401:
        print(f"  {_label('manager:')}{_YELLOW}UP{_RESET} — but rejected the token (401)")
        if not token:
            print(f"{_CONT}no token found; expected at {token_file}")
        else:
            print(f"{_CONT}token present but wrong; check {token_file}")
    else:
        h = resp if isinstance(resp, dict) else {}
        print(f"  {_label('manager:')}{_GREEN}UP{_RESET}  workers={h.get('workers_connected', '?')}"
              f"  jobs_pending={h.get('jobs_pending', '?')}  jobs_in_flight={h.get('jobs_in_flight', '?')}")

    # ── Token ──────────────────────────────────────────────────────────────
    if token:
        print(f"  {_label('token:')}present ({len(token)} chars)")
    else:
        print(f"  {_label('token:')}{_RED}missing{_RESET} — set MLSWEEP_TOKEN or write {token_file}")

    # ── GPUs (best effort) ──────────────────────────────────────────────────
    gpus = _query_gpu_stats()
    if gpus:
        print(f"  {_label('gpus:')}{len(gpus)} visible")
        for g in gpus:
            print(f"{_CONT}gpu{g['gpu']}  util={g['util_pct']}%  mem={g['mem_used_mb']}/{g['mem_total_mb']} MiB")
    else:
        print(f"  {_label('gpus:')}{_YELLOW}none visible{_RESET} (no nvidia-smi / rocm-smi output)")

    # ── Recent experiments (if authorized) ─────────────────────────────────
    if status not in (0, 401):
        e_status, experiments = _http_request("GET", _manager_url(manager, "/api/experiments"), token, timeout=10)
        if e_status == 200 and isinstance(experiments, list):
            ids = [e["experiment_id"] for e in experiments if isinstance(e, dict) and e.get("experiment_id")]
            if ids:
                print(f"  {_label('recent:')}{len(ids)} experiments; latest:")
                for eid in ids[-5:]:
                    print(f"{_CONT}{eid}")
        else:
            print(f"  {_label('recent:')}{_YELLOW}could not list{_RESET} (HTTP {e_status})")

    # ── Quick start ────────────────────────────────────────────────────────
    print()
    print(f"{_CYAN}Quick start:{_RESET}")
    print("  mlsweep manager")
    print(f"  mlsweep run sweeps/<file>.py --manager {manager} --stream")
    print(f"  mlsweep watch <experiment_id> --manager {manager}")
    print(f"  mlsweep fetch --manager {manager} --experiment <id>")
    print("  (or: mlsweep gen_makefile, then `make sweep-run S=sweeps/<file>.py`)")


# ── docs ───────────────────────────────────────────────────────────────────────


def _docs_cmd(argv: list[str]) -> None:
    parser = argparse.ArgumentParser(
        prog="mlsweep docs",
        description="Read the bundled mlsweep runbook.",
    )
    parser.add_argument("topic", nargs="?", default="README", help="Doc to show")
    parser.add_argument("--list", action="store_true", help="List available docs")
    args = parser.parse_args(argv)

    from importlib.resources import files

    docs_dir = files("mlsweep") / "docs"

    def print_available() -> None:
        print("Available docs (mlsweep docs <name>):")
        for name in sorted(p.name for p in docs_dir.iterdir() if p.name.endswith(".md")):
            print(f"  {name}")

    if args.list:
        print_available()
        return

    key = args.topic.lower().lstrip("./")
    filename = _DOC_ALIASES.get(key, key if key.endswith(".md") else key + ".md")
    target = docs_dir / filename
    if not target.is_file():
        print(f"{_RED}Unknown doc: {args.topic}{_RESET}")
        print_available()
        sys.exit(1)

    text = target.read_text()
    sys.stdout.write(text if text.endswith("\n") else text + "\n")


# ── gen_makefile ───────────────────────────────────────────────────────────────


def _gen_makefile_cmd(argv: list[str]) -> None:
    parser = argparse.ArgumentParser(
        prog="mlsweep gen_makefile",
        description="Write a standard mlsweep Makefile into the current directory.",
    )
    parser.add_argument("--force", action="store_true", help="Overwrite an existing Makefile")
    parser.add_argument("--dry-run", action="store_true", help="Print the Makefile instead of writing")
    args = parser.parse_args(argv)

    target = Path.cwd() / "Makefile"
    if args.dry_run:
        sys.stdout.write(_MAKEFILE_TEMPLATE)
        return

    if target.exists() and not args.force:
        print(f"{_RED}{target} already exists.{_RESET} Use --force to overwrite.")
        sys.exit(1)

    target.write_text(_MAKEFILE_TEMPLATE)
    print(f"{_GREEN}Wrote {target}{_RESET}")
    print("Now you can use:")
    print(_align([
        ("make sweep-run", "S=sweeps/<file>.py"),
        ("make sweep-watch", "E=<experiment_id>"),
        ("make sweep-fetch", "E=<experiment_id>"),
        ("make sweep-status", ""),
    ]))


# ── dispatch ───────────────────────────────────────────────────────────────────


def _forward(prog: str, fn: Callable[[], None], argv: list[str]) -> None:
    sys.argv = [prog, *argv]
    fn()


def main() -> None:
    argv = sys.argv[1:]

    if not argv:
        print(_HELP)
        return

    if argv[0] in ("-h", "--help", "help"):
        if len(argv) > 1:
            _docs_cmd(argv[1:])
        else:
            print(_HELP)
        return

    cmd, rest = argv[0], argv[1:]

    if cmd in ("-v", "--version", "version"):
        from importlib.metadata import version
        print(version("mlsweep"))
        return

    if cmd == "manager":
        from mlsweep.manager import main as _m
        _forward("mlsweep manager", _m, rest)
        return

    if cmd == "worker":
        from mlsweep.worker import main as _w
        _forward("mlsweep worker", _w, rest)
        return

    if cmd == "run":
        from mlsweep.run_sweep import main as _r
        _forward("mlsweep run", _r, rest)
        return

    if cmd == "watch":
        from mlsweep.run_sweep import _watch_cmd
        _watch_cmd(rest, prog="mlsweep watch")
        return

    if cmd == "fetch":
        from mlsweep.run_sweep import _fetch_cmd
        _fetch_cmd(rest, prog="mlsweep fetch")
        return

    if cmd in ("status", "doctor"):
        _status_cmd(rest)
        return

    if cmd == "docs":
        _docs_cmd(rest)
        return

    if cmd == "gen_makefile":
        _gen_makefile_cmd(rest)
        return

    print(f"{_RED}Unknown subcommand: {cmd}{_RESET}\n")
    print(_HELP)
    sys.exit(1)
